type Mutation {
	createAdminUser(password: String!): CreateAdminUserResponse
	login(userName: String!, password: String!): LoginResponse
	createEnsembleForUser(name: String!): CreateEnsembleForUserResponse
	createEnsembleToEnsemble(
		name: String!
		parentEnsembleId: String!
	): CreateEnsembleToEnsembleResponse
	logout: LogoutResponse
}
