type Mutation {
	createAdminUser(password: String!): CreateAdminUserResponse
	login(userName: String!, password: String!): LoginResponse
	createEnsembleForUser(name: String!): CreateEnsembleForUserResponse
	createEnsembleObject(
		name: String!
		parentEnsembleId: ID!
		type: String!
	): CreateEnsembleObjectResponse
	logout: LogoutResponse
}
