type Note implements EnsembleObject {
	id: ID!
	name: String!
	type: String!
	rows: [NoteRow!]!
}

input UpdatedNoteRow {
	rowNumber: Int!
	rowText: String
	onlyLineChange: Boolean
	lineRemoved: Boolean
}

type NoteRow {
	rowNumber: Int!
	text: String!
}

type UpdateNoteResponse {
	success: Boolean
}
